cmake_minimum_required(VERSION 3.10)
project(crust VERSION 1.0.0 LANGUAGES C)

# ==================================================================================================
# Global includes
# ==================================================================================================

# ==================================================================================================
# Global options
# ==================================================================================================

# ==================================================================================================
# Global Variables
# ==================================================================================================

# ==================================================================================================
# General compile flags
# ==================================================================================================

# ==================================================================================================
# General includes
# ==================================================================================================

# ==================================================================================================
# General libraries
# ==================================================================================================

# ==================================================================================================
# Sub-projects
# ==================================================================================================
add_subdirectory(src)
